services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\Fail2BanBundle\EventSubscriber\FailedLoginSubscriber:
        arguments: ['@monolog.logger.fail2ban']
